#!/bin/sh

## Start cron
systemctl enable tomcat9
sudo ufw allow from any to any port 8080 proto tcp
service tomcat start

## Run application
exec /app/app.py 
#exec /bin/bash

# Hand off to the CMD
#exec "$@"
